import type { BackendConfig, EntityDef, FieldDef } from "../schema/types";

const HEADER = "// Generated by frogcp. Do not edit.\n";

/**
 * Converts a snake_case / kebab-case entity name into a PascalCase TypeScript
 * identifier, e.g. "oauth_accounts" to "OauthAccounts".
 */
function toPascalCase(name: string): string {
  return name
    .split(/[_-]+/)
    .filter((part) => part.length > 0)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

/** Which side of the wire a type is emitted for: what a response reads back as
 * (`"row"`) vs what an insert/patch body may send (`"write"`). */
type TsContext = "row" | "write";

/**
 * Maps a field's declared type to the TypeScript type it reads back (`"row"`)
 * or may be written as (`"write"`).
 *
 * `date`/`timestamp` is the one type that differs by context. A row always
 * comes back as a string (Hono's `c.json` serializes a Drizzle `Date` via
 * `toISOString`, and `frogcp/client` parses with a bare `JSON.parse`, no
 * reviver), so typing it `Date` would let a consumer call `.getTime()` on a
 * runtime string. On write, `data/validate.ts` maps both to `z.coerce.date()`,
 * which accepts an ISO string or a `Date`.
 */
function fieldTypeToTs(field: FieldDef, context: TsContext): string {
  switch (field.type) {
    case "text":
    case "media":
    case "ref":
      return "string";
    case "select": {
      const options = field.options ?? [];
      return options.length > 0 ? options.map((opt) => JSON.stringify(opt)).join(" | ") : "string";
    }
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "date":
    case "timestamp":
      return context === "row" ? "string" : "string | Date";
    case "json":
      return "unknown";
  }
}

/**
 * Fields eligible for `Insert`/`Patch` shapes: never `hidden` (the client can't
 * set them) and never `auto` (the engine always populates them post-validation,
 * so the client never supplies one). `readonly` fields ARE included; rejecting
 * a client write to them is a runtime permissions concern, not a typing one.
 * `id` is never a key in `EntityDef.fields`, so it never appears here.
 */
function insertEligibleFields(entity: EntityDef): Array<[string, FieldDef]> {
  return Object.entries(entity.fields).filter(([, field]) => !field.hidden && !field.auto);
}

/** Mirrors `data/validate.ts`'s insert-mandatory rule: required, no default, not auto. */
function isInsertMandatory(field: FieldDef): boolean {
  return field.required && field.default === undefined && !field.auto;
}

/**
 * Emits the ROW interface, the shape a row reads back as in an API response.
 * `hidden` fields are excluded entirely (`DataEngine.stripHidden` guarantees
 * they never appear in a response). A non-`required` field compiles to a
 * nullable column and Drizzle returns SQL NULL as JS `null`, so the row type
 * marks it both optional and `| null`; a `required` field stays a bare
 * `field: T`. The implicit `id` is always present.
 */
function emitRowInterface(pascalName: string, entity: EntityDef): string {
  const lines: string[] = [`export interface ${pascalName} {`, "  id: string;"];
  for (const [name, field] of Object.entries(entity.fields)) {
    if (field.hidden) continue;
    const ts = fieldTypeToTs(field, "row");
    lines.push(field.required ? `  ${name}: ${ts};` : `  ${name}?: ${ts} | null;`);
  }
  lines.push("}");
  return lines.join("\n");
}

function emitInsertType(pascalName: string, entity: EntityDef): string {
  const fields = insertEligibleFields(entity);
  const lines: string[] = [`export interface Insert${pascalName} {`];
  for (const [name, field] of fields) {
    const ts = fieldTypeToTs(field, "write");
    lines.push(`  ${name}${isInsertMandatory(field) ? "" : "?"}: ${ts};`);
  }
  lines.push("}");
  return lines.join("\n");
}

function emitPatchType(pascalName: string, entity: EntityDef): string {
  const fields = insertEligibleFields(entity);
  const lines: string[] = [`export interface Patch${pascalName} {`];
  for (const [name, field] of fields) {
    const ts = fieldTypeToTs(field, "write");
    lines.push(`  ${name}?: ${ts};`);
  }
  lines.push("}");
  return lines.join("\n");
}

/**
 * Generates a `.d.ts` source string from a resolved `BackendConfig`: a `Row`,
 * `Insert`, and `Patch` interface per entity, plus a `ClientBackend` type
 * mapping each entity's original name to `{ row, insert, patch }`.
 * `frogcp/client`'s `createClient<TBackend>` is generic over this shape. Named
 * `ClientBackend` to avoid colliding with frogcp's own runtime `Backend`
 * interface. Pure function; writing the result to disk is the CLI's job.
 */
export function generateTypes(config: BackendConfig): string {
  const entries = Object.entries(config.entities);
  const pascalNames = new Map(entries.map(([name]) => [name, toPascalCase(name)]));

  const parts: string[] = [HEADER];

  for (const [name, entity] of entries) {
    const pascalName = pascalNames.get(name) ?? toPascalCase(name);
    parts.push(emitRowInterface(pascalName, entity));
    parts.push("");
    parts.push(emitInsertType(pascalName, entity));
    parts.push("");
    parts.push(emitPatchType(pascalName, entity));
    parts.push("");
  }

  parts.push("export type ClientBackend = {");
  for (const [name] of entries) {
    const pascalName = pascalNames.get(name) ?? toPascalCase(name);
    parts.push(
      `  ${JSON.stringify(name)}: { row: ${pascalName}; insert: Insert${pascalName}; patch: Patch${pascalName} };`,
    );
  }
  parts.push("};");
  parts.push("");

  return parts.join("\n");
}
